baseurl: "https://lorentz-host-microbe-interaction.netlify.app/"
title: "Review of Host Microbe Interaction with a Focus on Protein Metabolism"
author: Ben Lorentz
canonifyurls: yes
languagecode: en
theme: hugo-tanka
enableEmoji: yes
hasCJKLanguage: no
pygmentsstyle: vs
pygmentscodefences: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
params:
  faviconfile: images/favicon.png
  highlightjs: yes
  highlightjslanguages:
    - r
    - python
    - stan
  progressively: no
  sitename: Hugo Tanka Theme
  uselatex: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  primary:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: GitHub
      url: https://github.com/lorentzben
      weight: 3
    - name: Paper Notes
      url: /papers/
      weight: 4
    - name: Segment Notes
      url: /segments/
      weight: 5

permalinks:
    post = "/:year/:month/:day/:slug/"
    papers = "/:year/:month/:day/:slug/"
